### ISSUE TITLE
Windows instructions

### ISSUE THREAD

**Issue by mcg88** [fterh/heimdall#41]
Steps for Windows:

in the command prompt:
set the stage variable:
`set stage=prod`
then run the deployment using:
`yarn run deploy-dev`

Other notes:

- should region be set in .env rather than in serverless.yml ?
- I'd be in favor of a setting that enables catch-all aliases and the ability to blacklist individual ones

**Comment by fterh** [comment]
Hey, do you mind creating a pull request instead for Windows instructions? I don't want to risk updating it with wrong instructions since I can't verify (I'm running Mac).

- I feel that region is more of a configuration option than an environment variable
- That's a valid use case for sure, but I personally prefer a whitelist approach. Feel free to fork the project and modify it! For now, I won't be implementing that because it adds more complexity.
